apiVersion: v2
name: github-explorer
description: React UI for exploring GitHub using Apollo GraphQL
type: application
version: 0.2.3
appVersion: "v0.7.0"
maintainers:
  - name: mmontes11
    email: martin11lrx@gmail.com
