nameOverride: ""
fullnameOverride: ""

image:
  repository: mmontes11/github-explorer
  pullPolicy: IfNotPresent
  tag: "0.5.0"

service:
  type: ClusterIP
  port: 80

ingressRoute:
  enabled: false
  host: github-explorer.mmontes.duckdns.org
  entryPoints:
    - websecure

httpRoute:
  enabled: false
  host: github-explorer.mmontes.duckdns.org
  gatewayRef:
    name: traefik
    namespace: networking

resources: {}

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50

nodeSelector: {}
