nameOverride: ""
fullnameOverride: ""

image:
  repository: linuxserver/duckdns
  pullPolicy: IfNotPresent
  tag: 73eeb4c2-ls96

subdomains:
  - example.domain.org

timezone: Europe/Madrid

secretRef:
  name: duckdns

resources: {}

nodeSelector: {}
