nameOverride: ""
fullnameOverride: ""

image:
  repository: mmontes11/photoprism-auto-index
  tag: "220302-arm64"
  pullPolicy: IfNotPresent

env:
  PHOTOPRISM_DEBUG: true
  PHOTOPRISM_PUBLIC: false
  PHOTOPRISM_READONLY: false
  PHOTOPRISM_HTTP_COMPRESSION: "gzip"
  PHOTOPRISM_SITE_TITLE: "Media"
  PHOTOPRISM_SITE_CAPTION: "Your media center"
  PHOTOPRISM_SITE_AUTHOR: "mmontes"
  PHOTOPRISM_WORKERS: 2

secretRef:
  name: photoprism

persistence:
  enabled: true

  nas: &nas my.nas.hostname
  originalsPath: &originalsPath /photoprism/originals
  importPath: &importPath /photoprism/import
  storagePath: &storagePath /photoprism/storage

  volumes:
    - name: originals
      nfs:
        server: *nas
        path: /photoprism/originals
    - name: import
      nfs:
        server: *nas
        path: /photoprism/import
    - name: storage
      nfs:
        server: *nas
        path: /photoprism/storage

  volumeMounts:
    - name: originals
      mountPath: *originalsPath
    - name: import
      mountPath: *importPath
    - name: storage
      mountPath: *storagePath

database:
  driver: mysql
  host: photoprism-mariadb

sync:
  enabled: true
  cron: "0 6 * * *"
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 4Gi
      cpu: 2
  nodeSelector:
    kubernetes.io/arch: arm64

service:
  type: ClusterIP
  port: 80

ingressRoute:
  enabled: true
  host: photoprism.example.org
  entryPoints:
    - websecure

resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 256Mi
    cpu: 200m

nodeSelector:
  kubernetes.io/arch: arm64
