nameOverride: ""
fullnameOverride: ""

image:
  repository: photoprism/photoprism
  tag: "220302-bullseye"
  pullPolicy: IfNotPresent

env:
  PHOTOPRISM_AUTH: true
  PHOTOPRISM_HTTP_COMPRESSION: "gzip"
  PHOTOPRISM_LOG_LEVEL: info
  PHOTOPRISM_READONLY: true
  PHOTOPRISM_SITE_AUTHOR: "You"
  PHOTOPRISM_SITE_CAPTION: "Your media center"
  PHOTOPRISM_SITE_DESCRIPTION: "Your media center"

secretRef:
  name: photoprism

persistence:
  enabled: true

  nas: &nas my.nas.hostname
  originalsPath: &originalsPath /photoprism/originals
  importPath: &importPath /photoprism/import
  storagePath: &storagePath /photoprism/storage

  volumes:
    - name: originals
      nfs:
        server: *nas
        path: /photoprism/originals
    - name: import
      nfs:
        server: *nas
        path: /photoprism/import
    - name: storage
      nfs:
        server: *nas
        path: /photoprism/storage

  volumeMounts:
    - name: originals
      mountPath: *originalsPath
    - name: import
      mountPath: *importPath
    - name: storage
      mountPath: *storagePath

database:
  driver: mysql
  host: mariadb:3306

sync:
  enabled: true
  cron: "0 3,15 * * *"
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 4Gi
      cpu: 2
  nodeSelector: {}

service:
  type: ClusterIP
  port: 80

ingressRoute:
  enabled: true
  host: photoprism.org
  entryPoints:
    - websecure

resources:
  requests:
    memory: 128Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 1

nodeSelector: {}
