{{ $fullName := include "photoprism.fullname" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-environment
  labels:
    {{ include "photoprism.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-storage
  labels:
    {{ include "photoprism.labels" . | nindent 4 }}
data:
  PHOTOPRISM_HTTP_HOST: 0.0.0.0
  PHOTOPRISM_HTTP_PORT: "2342"
  PHOTOPRISM_DATABASE_DRIVER: {{ .Values.database.driver }}
  {{- with .Values.persistence }}
  PHOTOPRISM_ORIGINALS_PATH: {{ .originalsPath }}
  PHOTOPRISM_IMPORT_PATH: {{ .importPath }}
  PHOTOPRISM_STORAGE_PATH: {{ .storagePath }}
  {{ end }}