{{ $volumes := include "photoprism.volumes" . }}
{{ $volumeMounts := include "photoprism.volumeMounts" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "photoprism.fullname" . }}
  labels:
    {{ include "photoprism.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{ include "photoprism.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount | default 1 }}
  template:
    metadata:
      labels:
        {{ include "photoprism.selectorLabels" . | nindent 8 }}
    spec:
      {{ with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.sync.affinity }}
      affinity:
        {{ toYaml . | nindent 12 }}
      {{ end }}
      containers:
      - name: photoprism
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{ include "photoprism.envFrom" . | nindent 8 }}
        {{ include "photoprism.env" . | nindent 8 }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          {{ with .Values.livenessProbe }}
          {{ toYaml . | nindent 10 }}
          {{ end }}
        readinessProbe:
          httpGet:
            path: /
            port: http
          {{ with .Values.readinessProbe }}
          {{ toYaml . | nindent 10 }}
          {{ end }}
        {{ with .Values.resources }}
        resources:
          {{ toYaml . | nindent 10 }}
        {{ end }}
        ports:
        - containerPort: 2342
          name: http
        {{ if $volumeMounts}}
        volumeMounts:
          {{ $volumeMounts | nindent 10 }}
        {{ end }}
      {{ with $volumes }}
      volumes:
        {{ $volumes | nindent 8 }}
      {{ end }}