photoprism:
  secretNameOverride: xiaowen-media

  config:
    PHOTOPRISM_SITE_TITLE: "ChampiCloud"
    PHOTOPRISM_SITE_CAPTION: "xiaowen media center"
    PHOTOPRISM_SITE_AUTHOR: "xiaowen"
    PHOTOPRISM_AUTO_INDEX_CRON: "0 2 * * *"

  persistence:
    enabled: true

    nas: &nas 192.168.0.120
    originalsPath: &originalsPath /photoprism/originals
    importPath: &importPath /photoprism/import
    storagePath:   &storagePath    /photoprism/storage

    volumes:
    - name: originals
      nfs:
        server: *nas
        path: /volume1/homes/xiaowen
    - name: import
      nfs:
        server: *nas
        path: /volume1/photoprism/xiaowen/import
    - name: storage
      nfs:
        server: *nas
        path: /volume1/photoprism/xiaowen/storage
        
    volumeMounts:
    - name: originals
      mountPath: *originalsPath
    - name: import
      mountPath: *importPath
    - name: storage
      mountPath: *storagePath

  database:
    driver: mysql
    host: xiaowen-media-mariadb

  service:
    type: ClusterIP
    port: 80

  ingressRoute:
    enabled: true
    host: xiaomedia.mmontes-dev.duckdns.org
    entryPoints:
      - websecure

  mariadb:
    secretNameOverride: xiaowen-media
