apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cockroach-operator-rolebinding
  labels:
    {{ include "cockroachdb-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cockroach-operator-role
subjects:
  - kind: ServiceAccount
    name: cockroach-operator-sa
    namespace: {{ .Release.Namespace }}