apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cockroach-operator-role
  labels:
    {{ include "cockroachdb-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"