{{ $fullName := include "mongodb.fullname" . }}
{{ if .Values.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $fullName }}-backup
  labels:
    {{ include "mongodb.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.backup.cron | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 5
      parallelism: 1
      completions: 1
      template:
        spec:
          {{ with .Values.nodeSelector }}
          nodeSelector:
            {{ toYaml . | nindent 16 }}
          {{ end }}
          restartPolicy: OnFailure
          containers:
          - name: {{ $fullName }}-backup
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command:
              - mongodump
            args:
              - "--uri"
              - "mongodb://{{ $fullName }}:27017"
              - "--out"
              - "/backup"
            volumeMounts:
            - name: backup
              mountPath: /backup
          {{ include "mongodb.backupVolume" . | nindent 10 }} 
{{ end }}