{{ $fullName := include "mongodb.fullname" . }}
{{ if .Values.backup.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $fullName }}-backup
  labels:
    {{ include "mongodb.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.backup.cron | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          {{ with .Values.nodeSelector }}
          nodeSelector:
            {{ toYaml . | nindent 16 }}
          {{ end }}
          containers:
          - name: {{ $fullName }}-backup
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command:
              - mongodump
            args:
              - "--uri"
              - "mongodb://{{ $fullName }}:{{ .Values.port }}"
              - "--out"
              - "/backup"
            volumeMounts:
            - name: {{ $fullName  }}-backup
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: {{ $fullName  }}-backup
            persistentVolumeClaim:
              claimName: {{ $fullName }}-backup
{{ end }}