{{ if .Values.backup.enabled }}
{{ $fullName := include "mongodb.fullname" . }}
{{ $labels := include "mongodb.labels" . }}
{{ with .Values.backup.volume.pvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-backup
  labels:
    {{ $labels | nindent 4 }}
spec:
  storageClassName: {{ .className }}
  accessModes: {{ .accessModes }}
  resources:
    requests:
      storage: {{ .size }}
{{ end }}
{{ end }}