{{ $fullName := include "mongodb.fullname" . }}
{{ $selectorLabels := include "mongodb.selectorLabels" . }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullName  }}
  labels:
    {{ include "mongodb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{ $selectorLabels | nindent 6 }}
  serviceName: {{ $fullName }}
  template:
    metadata:
      labels:
        {{ $selectorLabels | nindent 8 }}
    spec:
      {{ with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      containers:
        - name: mongo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - mongod
          args: 
          - --bind_ip=0.0.0.0
          - --dbpath=/data/db    
          {{ with .resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{ end }}
          ports:
            - containerPort: {{ .Values.port }}
          livenessProbe:
            exec:
              command:
              - mongo
              - --eval
              - "db.adminCommand('ping')"
            {{ with .Values.livenessProbe }}
            {{ toYaml . | nindent 12 }}
            {{ end }}
          readinessProbe:
            exec:
              command:
              - mongo
              - --eval
              - "db.adminCommand('ping')"
            {{ with .Values.readinessProbe }}
            {{ toYaml . | nindent 12 }}
            {{ end }}
          volumeMounts:
            - name: {{ $fullName  }}
              mountPath: /data/db
            {{ if .Values.backup.enabled }}
            - name: {{ $fullName  }}-backup
              mountPath: /backup
            {{ end }}
      volumes:
        - name: {{ $fullName  }}
          persistentVolumeClaim:
            claimName: {{ $fullName  }}
        {{ if .Values.backup.enabled }}
        - name: {{ $fullName  }}-backup
          persistentVolumeClaim:
            claimName: {{ $fullName }}-backup
        {{ end }}
