{{- if .Values.httpRoute.enabled -}}
{{- $fullName := include "photoprism.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{ include "photoprism.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.httpRoute.gatewayRef.name }}
      namespace: {{ .Values.httpRoute.gatewayRef.namespace }}
  hostnames:
    - {{ .Values.httpRoute.host }}
  rules:
    - backendRefs:
      - kind: Service
        name: {{ $fullName }}
        port: {{ .Values.service.port }}
{{- end }}