nameOverride: ""
fullnameOverride: ""

# secret with this variables: 
# CLICKHOUSE_URL
# NATS_URL
# MIGRATIONS_URL
secretNameOverride: crypto-trade

api: 
  image:
    repository: mmontes11/crypto-trade-api
    pullPolicy: IfNotPresent
    tag: "v0.9.3"

  service:
    type: ClusterIP
    port: 80
  
  livenessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 3
    periodSeconds: 15
    
  readinessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 3
    periodSeconds: 15

  ingressRoute:
    enabled: true
    host: crypto-trade.mmontes-dev.duckdns.org
    entryPoints:
      - websecure

  env: production

  resources:
    requests:
      cpu: 100m
      memory: "128Mi"
    limits:
      cpu: 300m
      memory: "512Mi"

  replicaCount: 1

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50

  nodeSelector: {}

publisher:
  image:
    repository: mmontes11/crypto-trade-publisher
    pullPolicy: IfNotPresent
    tag: "v0.9.3"
  
  env: production

  subject: trades

  publishIntervalMs: 4000

  numPublishers: 4

  resources:
    requests:
      cpu: 100m
      memory: "128Mi"
    limits:
      cpu: 300m
      memory: "512Mi"

  replicaCount: 1

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50

  nodeSelector: {}

subscriber:
  image:
    repository: mmontes11/crypto-trade-subscriber
    pullPolicy: IfNotPresent
    tag: "v0.9.3"

  env: production

  subject: trades

  numSubscribers: 4

  resources:
    requests:
      cpu: 100m
      memory: "128Mi"
    limits:
      cpu: 300m
      memory: "512Mi"

  replicaCount: 1

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50

  nodeSelector: {}

nats:
  nameOverride: crypto-trade-nats
  image: nats:2.1.9-alpine3.12
  pullPolicy: IfNotPresent

  cluster:
    enabled: true
    replicas: 3
    noAdvertise: false

  natsbox:
    enabled: false
    image: synadia/nats-box:0.4.0
    pullPolicy: IfNotPresent

  reloader:
    enabled: false
    image: connecteverything/nats-server-config-reloader:0.6.0
    pullPolicy: IfNotPresent

  exporter:
    enabled: true
    image: natsio/prometheus-nats-exporter:0.7.0
    pullPolicy: IfNotPresent
    serviceMonitor:
      enabled: true
      namespace: monitoring
      labels:
        release: monitoring
      path: /metrics

clickhouse:
  timezone: "UTC"

  clickhouse:
    image: "lunalabsltd/clickhouse-server"
    imageVersion: "20.6.7.4-arm"
    imagePullPolicy: "IfNotPresent"
    
    replicas: "1"

    configmap:
      remote_servers:
        replica:
          backup:
            enabled: false

  tabix: 
    enabled: false

