apiVersion: v2
name: iot
description: General purpose Internet of Things platform
type: application
version: 0.3.1
appVersion: v3.8.0
maintainers:
  - name: mmontes11
    email: martin11lrx@gmail.com
