apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "duckdns.fullname" . }}
  labels:
    {{ include "duckdns.labels" . | nindent 4 }}
data:
  LOG_FILE: "true"
  PGID: "1000"
  PUID: "1000"
  SUBDOMAINS: {{ join "," .Values.subdomains }}
  TZ: {{ .Values.timezone }}
