{{ $fullName := include "duckdns.fullname" . }}
{{ $selectorLabels := include "duckdns.selectorLabels" . }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $fullName }}
  labels:
    {{ include "duckdns.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{ $selectorLabels | nindent 6 }}
  template:
    metadata:
      labels:
        {{ $selectorLabels | nindent 8 }}
    spec:
      containers:
        - name: {{ $fullName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ with .Values.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{ end }}
          envFrom:
            - configMapRef:
                name: {{ $fullName }}
            {{ with .Values.secretRef }}
            - secretRef:
                {{ toYaml . | nindent 16 }}
            {{ end }}
      {{ with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end}}