{{ $fullName := include "pi-hole.fullname" . }}
{{ $labels := include "pi-hole.labels" . }}
{{ $selectorLabels := include "pi-hole.selectorLabels" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-http
  labels: 
    {{ $labels | nindent 4 }}
spec:
  selector: 
    {{ $selectorLabels | nindent 4 }}
  {{ with .Values.service }}
  type: ClusterIP
  ports:
    - port: {{ .httpPort }}
      targetPort: {{ .httpPort }}
      protocol: TCP
      name: http
  {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-dns
  labels: 
    {{ $labels | nindent 4 }}
spec:
  selector: 
    {{ $selectorLabels | nindent 4 }}
  {{ with .Values.service }}
  type: {{ .type }}
  ports:
    - port: {{ .dnsPort }}
      targetPort: {{ .dnsPort }}
      nodePort: {{ .dnsPort }}
      protocol: TCP
      name: dns-tcp
    - port: {{ .dnsPort }}
      targetPort: {{ .dnsPort }}
      nodePort: {{ .dnsPort }}
      protocol: UDP
      name: dns-udp
  {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-dhcp
  labels: 
    {{ $labels | nindent 4 }}
spec:
  selector: 
    {{ $selectorLabels | nindent 4 }}
  {{ with .Values.service }}
  type: {{ .type }}
  ports:
    - port: {{ .dhcpPort }}
      targetPort: {{ .dhcpPort }}
      nodePort: {{ .dhcpPort }}
      protocol: TCP
      name: dhcp
  {{ end }}

