{{ if $.Values.serviceExamples.enabled }}
{{ with $.Values.serviceExamples.stock }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gotway.fullnameStock" $ }}
  labels:
    {{ include "gotway.labelsStock" $ | nindent 4 }}
data:
  PORT: {{ .service.port | quote }}
  REDIS_URL: {{ .redis.address }}
  REDIS_DATABASE: {{ .redis.db | quote }}
  REDIS_PREFIX: {{ .redis.prefix | quote }}
  REDIS_TTL_DEFAULT: {{ .redis.ttlDefault | quote }}
  REDIS_TTL_MAX: {{ .redis.ttlMax | quote }}
{{ end }}
{{ end }}