{{ $fullName := include "traefik.fullname" . }}
{{ with .Values.serviceMonitor }}
{{ if .enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullName }}
  namespace: {{ .namespace }}
  {{ with .labels }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{ end }}
spec:
  selector:
      matchLabels:
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/name: traefik
  namespaceSelector:
    any: true
  endpoints:
    - targetPort: 9000
      path: /metrics
{{ end }}
{{ end }}