{{ $fullName := include "traefik.fullname" . }}
{{ $labels := include "traefik.labels" . }}
{{ with .Values.dashboard }}
{{ if .enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}
  labels:
    {{ $labels | nindent 4 }}
spec:
  basicAuth:
    secret: {{ .secret }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{ $labels | nindent 4 }}
spec:
  entrypoints:
  {{ range $entrypoint := .entrypoints }}
    - {{ $entrypoint }}
  {{ end }}
  routes:
    - kind: Rule
      match: Host(`{{ .host }}`)
      middlewares:
        - name: {{ $fullName }}
      services:
        - name: api@internal
          kind: TraefikService
{{ end }}
{{ end }}