nameOverride: ""
fullnameOverride: ""

image:
  repository: mariadb
  tag: "10.7.3"
  pullPolicy: IfNotPresent

storage:
  size: 4Gi
  className: local-path
  accessModes:
    - "ReadWriteOnce"

# Check the docs to configure auth: https://hub.docker.com/_/mariadb
secretRef:
  name: mariadb

resources: {}

nodeSelector: {}

podDisruptionBudget:
  enabled: false
  minAvailable: 1
