apiVersion: v1
kind: Service
metadata:
  name: {{ include "github-explorer.fullname" . }}
  labels: {{ include "github-explorer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      
  selector: {{ include "github-explorer.selectorLabels" . | nindent 4 }}
