{{ $fullName := include "redis.fullname" . }}
{{ $selectorLabels := include "redis.selectorLabels" . }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullName  }}
  labels:
    {{ include "redis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{ $selectorLabels | nindent 6 }}
  serviceName: {{ $fullName }}
  template:
    metadata:
      labels:
        {{ $selectorLabels | nindent 8 }}
    spec:
      {{ with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      containers:
        - name: {{ $fullName  }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ with .Values.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{ end }}
          ports:
            - containerPort: 6379
              name: redis
  {{ with .Values.storage }}
          volumeMounts:
            - name: storage
              mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: {{ .accessModes }}
      storageClassName: {{ .className }}
      resources:
        requests:
          storage: {{ .size }}
  {{ end }}
