nameOverride: ""
fullnameOverride: ""

image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: 4.4.13

storage:
  size: 8Gi
  className: standard
  accessModes:
    - "ReadWriteOnce"

backup:
  enabled: true
  cron: "0 3 * * *"
  storage:
    size: 8Gi
    className: standard
    accessModes:
      - "ReadWriteOnce"

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10

resources: {}

nodeSelector: {}

prometheus-mongodb-exporter:
  image:
    repository: mmontes11/mongodb-prometheus-exporter
    tag: v0.12.0
  extraArgs:
    - --collect.collection
    - --collect.database
    - --collect.indexusage
    - --collect.topmetrics
    - --collect.connpoolstats
  port: "9113"
  service:
    port: 9113
    type: ClusterIP
  mongodb:
    uri: "mongodb://mongodb:27017"
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    additionalLabels:
      release: kube-prometheus-stack
