nameOverride: ""
fullnameOverride: ""

image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: 4.4.4

storage: 8Gi

port: 27017

backup:
  enabled: true
  secretNameOverride: ""
  storage: 
    size: 8Gi
    class: nfs
  cron: 
    image:
      repository: mmontes11/mongodb-backup
      pullPolicy: IfNotPresent
      tag: vdebug
    schedule: "* 3 * * *"

resources: {}

nodeSelector:
  kubernetes.io/arch: arm64

prometheus-mongodb-exporter:
  image:
    repository: mmontes11/mongodb-prometheus-exporter
    tag: v0.12.0
  extraArgs:
    - --collect.collection
    - --collect.database
    - --collect.indexusage
    - --collect.topmetrics
    - --collect.connpoolstats
  port: "9113"
  service:
    port: 9113
    type: ClusterIP
  livenessProbe:
    httpGet:
      path: /
      port: metrics
    initialDelaySeconds: 10
  readinessProbe:
    httpGet:
      path: /
      port: metrics
    initialDelaySeconds: 10
  mongodb:
    uri: "mongodb://mongo:27017"
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    namespace: monitoring
    additionalLabels:
      release: prometheus
