nameOverride: ""
fullnameOverride: ""

image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: 4.4.13

storage:
  size: 8Gi
  className: standard
  accessModes:
    - "ReadWriteOnce"

backup:
  enabled: true
  cron: "0 3 * * *"
  volume:
    nfs:
      server: my.nas.hostname
      path: /volume
    pvc:
      size: 8Gi
      className: standard
      accessModes:
        - "ReadWriteOnce"

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10

resources: {}

nodeSelector: {}
