nameOverride: ""
fullnameOverride: ""

image:
  repository: redis
  pullPolicy: IfNotPresent
  tag: 6.2.6-alpine3.15

storage:
  size: 1Gi
  className: standard
  accessModes:
    - "ReadWriteOnce"

resources: {}

nodeSelector: {}

podDisruptionBudget:
  enabled: false
  minAvailable: 1
