{{ $fullName := include "gotway.fullname" . }}
{{ $labels := include "gotway.labels" . }}
{{ $selectorLabels := include "gotway.selectorLabels" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{ $labels | nindent 4 }}
  {{ with .Values.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{ end }}
spec:
  type: {{ .Values.service.type }}
  {{ with .Values.service.spec }}
  {{ toYaml . | nindent 2 }}
  {{ end }}
  ports:
    - port: {{ .Values.service.port }}
      {{ if or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer") }}
      {{ with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{ end }}
      {{ end }}
  selector:
    {{ $selectorLabels | nindent 4 }}
---
{{ if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-metrics
  labels:
    {{ $labels | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.monitoring.port }}
      name: metrics
  selector:
    {{ $selectorLabels | nindent 4 }}
{{ end }}