apiVersion: v1
kind: Service
metadata:
  name: {{ include "gotway.fullname" . }}
  labels:
    {{- include "gotway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.interalPort }}
      nodePort: {{ .Values.service.externalPort }}
  selector:
    {{ include "gotway.selectorLabels" . | nindent 4 }}
