apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bankroach.fullname" . }}
  labels:
    {{ include "bankroach.labels" . | nindent 4 }}
data:
  NUM_ACCOUNTS: {{ .Values.numAccounts | quote }}
  INITIAL_BALANCE: {{ .Values.initialBalance | quote }}
  SCHEDULE_INTERVAL_SECONDS: {{ .Values.scheduleIntervalSeconds | quote }}
  NUM_WORKERS: {{ .Values.numWorkers | quote }}
  ENV: {{ .Values.env }}
  LOG_LEVEL: {{ .Values.logLevel }}