{{ with $.Values.nginx }}
{{ $fullName := include "iot.fullnameNginx" $ }}

{{ if .ingressRoute.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{ include "iot.labels" $ | nindent 4 }}
spec:
  entryPoints:
    {{ range $entrypoint := .ingressRoute.entryPoints }}
    - {{ $entrypoint }}
    {{ end }}
  routes:
    - kind: Rule
      match: Host(`{{ .ingressRoute.host }}`)
      services:
        - kind: Service
          name: {{ $fullName }}
          port: {{ .service.port }}
{{ end }}

{{ if .httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{ include "iot.labels" $ | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .httpRoute.gatewayRef.name }}
      namespace: {{ .httpRoute.gatewayRef.namespace }}
  hostnames:
    - {{ .httpRoute.host }}
  rules:
    - backendRefs:
      - kind: Service
        name: {{ $fullName }}
        port: {{ .service.port }}
{{ end }}

{{ end }}