{{ with $.Values.nginx }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iot.fullnameNginx" $ }}
  labels: 
    {{ include "iot.labels" $ | nindent 4 }}
spec:
  type: {{ .service.type }}
  sessionAffinity: ClientIP
  ports:
    - port: {{ .service.port }}
  selector: 
    {{ include "iot.selectorLabelsNginx" $ | nindent 4 }}
{{ end }}