apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scheduledechos.mmontes.io
spec:
  group: mmontes.io
  names:
    kind: ScheduledEcho
    listKind: ScheduledEchoList
    plural: scheduledechos
    singular: scheduledecho
    shortNames:
      - sec
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
                schedule:
                  type: string
              required:
                - message
                - schedule
