apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cockroach-operator-default
  labels:
    {{ include "cockroachdb-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cockroach-operator-role
subjects:
  - name: cockroach-operator-sa
    kind: ServiceAccount