nameOverride: ""
fullnameOverride: ""

image:
  repository: linuxserver/duckdns
  pullPolicy: IfNotPresent
  tag: 73eeb4c2-ls96

subdomains:
  - example.domain.org

timezone: Europe/Madrid

secretRef:
  name: duckdns

replicas: 2

resources: {}

nodeSelector: {}

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - duckdns
        topologyKey: kubernetes.io/hostname
