apiVersion: v2
name: mongodb
description: MongoDB with metrics compatible with ARM
type: application
version: 0.5.0
appVersion: 1.16.0
maintainers:
  - name: mmontes11
    email: martin11lrx@gmail.com
